'use client';

import { useState } from 'react';
import Link from 'next/link';
import { PROFESSION_CATEGORIES, getAllProfessions, ProfessionCard, ProfessionCategory } from '@/lib/professional-ethics';
import {
  ChevronDown, ChevronRight, ArrowRight, Scale, Briefcase, BookOpen,
  BrainCircuit, HeartPulse, Leaf, Gavel, Newspaper, Filter,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';

const CATEGORY_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  governance: Scale,
  commerce: Briefcase,
  'knowledge-education': BookOpen,
  'science-technology': BrainCircuit,
  'health-care': HeartPulse,
  environment: Leaf,
  'law-justice': Gavel,
  'media-narrative': Newspaper,
};

const AMPLIFICATION_BLOCKS = [
  {
    title: 'Amplification Principle',
    body: 'Every profession magnifies one psychological faculty. Power magnifies the ego. Wealth magnifies attachment. Knowledge magnifies pride. Healing magnifies the messianic impulse. Technical control magnifies the illusion of mastery.',
  },
  {
    title: 'Ethical Risk',
    body: 'Unregulated amplification produces characteristic forms of corruption. Each profession carries predictable failure modes that are not incidental but structurally embedded in the work itself.',
  },
  {
    title: 'Psychological Calibration',
    body: 'Inner discipline stabilises authority and responsibility. Sufi ethics provides a systematic framework for monitoring and correcting the psychological distortions generated by sustained professional power.',
  },
  {
    title: 'Transmission Integration',
    body: 'Professional integrity must align with contemplative practice. Ethical conduct in the professional domain and spiritual development in the inner domain are not separate projects — they reinforce or undermine each other.',
  },
];

function ProfessionCardComponent({ profession }: { profession: ProfessionCard }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="border border-white/6 rounded-xl bg-white/[0.015] hover:border-[#C8A75E]/20 transition-all duration-300">
      <button
        className="w-full text-left p-5 flex items-start justify-between gap-4 group"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex-1 min-w-0">
          <h3 className="text-sm font-semibold text-[#F5F3EE] group-hover:text-[#C8A75E] transition-colors leading-snug mb-2">
            {profession.title}
          </h3>
          <p className="text-[13px] text-[#AAB0D6]/70 leading-relaxed line-clamp-2">
            {profession.description}
          </p>
        </div>
        <ChevronDown
          className={`h-4 w-4 text-[#AAB0D6]/40 group-hover:text-[#C8A75E] flex-shrink-0 mt-0.5 transition-all duration-200 ${expanded ? 'rotate-180 text-[#C8A75E]' : ''}`}
        />
      </button>

      {expanded && (
        <div className="px-5 pb-5 space-y-5 border-t border-white/6 pt-5">
          <div>
            <p className="text-[10px] font-bold text-[#C8A75E] uppercase tracking-widest mb-2">
              Spiritual Orientation
            </p>
            <p className="text-[13px] text-[#D8D4CC] leading-relaxed">
              {profession.spiritualOrientation}
            </p>
          </div>

          <div>
            <p className="text-[10px] font-bold text-[#C8A75E] uppercase tracking-widest mb-2">
              Ethical Axis
            </p>
            <ul className="space-y-1.5">
              {profession.ethicalAxis.map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="text-[#C8A75E] text-[8px] mt-1.5">&#9632;</span>
                  <span className="text-[13px] text-[#D8D4CC]">{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <p className="text-[10px] font-bold text-[#C8A75E] uppercase tracking-widest mb-2">
              Psychological Discipline Required
            </p>
            <p className="text-[13px] text-[#D8D4CC] leading-relaxed">
              {profession.psychologicalDiscipline}
            </p>
          </div>

          <div>
            <p className="text-[10px] font-bold text-[#C8A75E] uppercase tracking-widest mb-2">
              Common Distortions
            </p>
            <ul className="space-y-1.5">
              {profession.commonDistortions.map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="text-[#AAB0D6]/50 text-[8px] mt-1.5">&#9632;</span>
                  <span className="text-[13px] text-[#AAB0D6]/80">{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {profession.linkedDomains.length > 0 && (
            <div>
              <p className="text-[10px] font-bold text-[#C8A75E] uppercase tracking-widest mb-2">
                Linked NextGEN Discipline Domains
              </p>
              <div className="flex flex-wrap gap-2">
                {profession.linkedDomains.map((domain) => (
                  <Link
                    key={domain.slug}
                    href={`/nextgen-sufi-seeker`}
                    className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full border border-[#C8A75E]/25 bg-[#C8A75E]/8 text-[#C8A75E] text-xs hover:bg-[#C8A75E]/15 hover:border-[#C8A75E]/50 transition-colors"
                  >
                    {domain.label}
                    <ChevronRight className="h-3 w-3" />
                  </Link>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function CategorySection({ category, activeFilter }: { category: ProfessionCategory; activeFilter: string | null }) {
  const Icon = CATEGORY_ICONS[category.id] ?? BookOpen;
  const [collapsed, setCollapsed] = useState(false);

  if (activeFilter && activeFilter !== category.id) return null;

  return (
    <div className="space-y-4">
      <button
        className="w-full flex items-center justify-between gap-3 group"
        onClick={() => setCollapsed(!collapsed)}
      >
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-[#C8A75E]/10 border border-[#C8A75E]/20 flex items-center justify-center flex-shrink-0">
            <Icon className="h-4 w-4 text-[#C8A75E]" />
          </div>
          <div className="text-left">
            <h2 className="text-base font-bold text-[#F5F3EE] group-hover:text-[#C8A75E] transition-colors">
              {category.title}
            </h2>
            <p className="text-[12px] text-[#AAB0D6]/60 leading-snug mt-0.5 hidden sm:block">
              {category.description}
            </p>
          </div>
        </div>
        <ChevronDown
          className={`h-4 w-4 text-[#AAB0D6]/40 flex-shrink-0 transition-transform duration-200 ${collapsed ? '' : 'rotate-180'}`}
        />
      </button>

      {!collapsed && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 ml-0 sm:ml-11">
          {category.professions.map((profession) => (
            <ProfessionCardComponent key={profession.id} profession={profession} />
          ))}
        </div>
      )}
    </div>
  );
}

export default function AppliedProfessionalEthicsPage() {
  const [activeFilter, setActiveFilter] = useState<string | null>(null);
  const allProfessions = getAllProfessions();

  return (
    <div className="min-h-screen bg-[#08091A]">
      <div className="max-w-6xl mx-auto px-6 py-16 sm:px-8 lg:px-12">

        {/* Breadcrumb */}
        <div className="flex items-center gap-2 mb-10 text-xs text-[#AAB0D6]/50">
          <Link href="/nextgen-sufi-seeker" className="hover:text-[#AAB0D6] transition-colors">
            NextGEN Sufi Seeker Platform
          </Link>
          <ChevronRight className="h-3 w-3" />
          <span className="text-[#AAB0D6]/80">Applied Professional Ethics</span>
        </div>

        {/* Hero */}
        <div className="mb-14">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-[#C8A75E]/25 bg-[#C8A75E]/8 mb-6">
            <span className="text-[10px] font-bold text-[#C8A75E] uppercase tracking-widest">
              Structural Framework
            </span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-serif font-bold text-[#F5F3EE] leading-tight mb-4">
            Applied Professional Ethics
          </h1>
          <p className="text-lg text-[#AAB0D6] leading-relaxed max-w-2xl mb-6">
            Spiritual anthropology of professional responsibility.
          </p>
          <p className="text-[15px] text-[#AAB0D6]/80 leading-relaxed max-w-3xl">
            Every profession amplifies a specific psychological faculty — power, knowledge, wealth, healing, or control.
            Left unregulated, these amplifications produce characteristic forms of ethical corruption. Sufi ethics provides
            systematic calibration mechanisms: inner-discipline frameworks that stabilise authority, restrain ego inflation,
            and anchor professional conduct in principled intention.
          </p>
        </div>

        {/* Conceptual Framework */}
        <section className="mb-16">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-0.5 h-5 bg-[#C8A75E] rounded-full" />
            <h2 className="text-xs font-bold text-[#C8A75E] uppercase tracking-widest">
              The Spiritual Structure of Work
            </h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {AMPLIFICATION_BLOCKS.map((block) => (
              <div
                key={block.title}
                className="bg-[#0F1430]/60 border border-white/6 rounded-xl p-5"
              >
                <p className="text-[11px] font-bold text-[#C8A75E] uppercase tracking-widest mb-3">
                  {block.title}
                </p>
                <p className="text-[13px] text-[#AAB0D6]/80 leading-relaxed">
                  {block.body}
                </p>
              </div>
            ))}
          </div>
        </section>

        <Separator className="bg-[rgba(200,167,94,0.10)] mb-14" />

        {/* Filter Bar */}
        <div className="flex items-center gap-3 mb-8 flex-wrap">
          <div className="flex items-center gap-1.5 text-xs text-[#AAB0D6]/50 mr-1">
            <Filter className="h-3.5 w-3.5" />
            <span>Filter</span>
          </div>
          <button
            onClick={() => setActiveFilter(null)}
            className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors border ${
              activeFilter === null
                ? 'bg-[#C8A75E]/15 border-[#C8A75E]/40 text-[#C8A75E]'
                : 'border-white/10 text-[#AAB0D6]/60 hover:text-[#AAB0D6] hover:border-white/20'
            }`}
          >
            All Domains ({PROFESSION_CATEGORIES.length})
          </button>
          {PROFESSION_CATEGORIES.map((cat) => {
            const Icon = CATEGORY_ICONS[cat.id] ?? BookOpen;
            return (
              <button
                key={cat.id}
                onClick={() => setActiveFilter(activeFilter === cat.id ? null : cat.id)}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-colors border ${
                  activeFilter === cat.id
                    ? 'bg-[#C8A75E]/15 border-[#C8A75E]/40 text-[#C8A75E]'
                    : 'border-white/10 text-[#AAB0D6]/60 hover:text-[#AAB0D6] hover:border-white/20'
                }`}
              >
                <Icon className="h-3 w-3" />
                {cat.title.split(' ')[0]}
              </button>
            );
          })}
        </div>

        {/* Profession Grid */}
        <section className="space-y-12 mb-16">
          {PROFESSION_CATEGORIES.map((category) => (
            <CategorySection key={category.id} category={category} activeFilter={activeFilter} />
          ))}
        </section>

        <Separator className="bg-[rgba(200,167,94,0.10)] mb-14" />

        {/* Integration Section */}
        <section className="mb-10">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-0.5 h-5 bg-[#C8A75E] rounded-full" />
            <h2 className="text-xs font-bold text-[#C8A75E] uppercase tracking-widest">
              Professional Pathway Integration
            </h2>
          </div>

          <p className="text-[15px] text-[#AAB0D6]/80 leading-relaxed max-w-3xl mb-8">
            Each professional ethical framework within this module connects directly to the NextGEN Platform&apos;s
            development infrastructure. Discipline selection, assessment, and membership tiers are calibrated against
            the professional ethics of your specific domain.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            {[
              { label: 'Discipline Channels', desc: '60+ domain-specific inquiry tracks aligned with professional context' },
              { label: 'Assessment Levels', desc: 'Evaluative frameworks mapping professional ethical calibration against developmental stages' },
              { label: 'Emotional Intelligence', desc: 'Structured modules for psychological self-examination in high-stakes roles' },
              { label: 'Leadership Evaluation', desc: 'Comprehensive frameworks for authority-holders to audit their ethical functioning' },
            ].map((item) => (
              <div
                key={item.label}
                className="bg-[#0F1430]/60 border border-white/6 rounded-xl p-4"
              >
                <p className="text-[11px] font-bold text-[#C8A75E] uppercase tracking-widest mb-2">
                  {item.label}
                </p>
                <p className="text-[12px] text-[#AAB0D6]/70 leading-relaxed">
                  {item.desc}
                </p>
              </div>
            ))}
          </div>

          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
            <Link
              href="/nextgen-sufi-seeker"
              className="inline-flex items-center gap-2 px-5 py-3 rounded-lg bg-[#C8A75E] text-[#08091A] text-sm font-bold hover:bg-[#D4B870] transition-colors"
            >
              Explore Your Discipline
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/assessment/take"
              className="inline-flex items-center gap-2 px-5 py-3 rounded-lg border border-[#C8A75E]/30 text-[#C8A75E] text-sm font-semibold hover:bg-[#C8A75E]/10 transition-colors"
            >
              Take Personal Assessment
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </section>

      </div>
    </div>
  );
}
