export type PowerType = 'State' | 'Economic' | 'Cultural' | 'Spiritual' | 'Technical' | 'Institutional';
export type RiskLevel = 'High Authority' | 'Moderate Authority' | 'Distributed Influence';
export type EthicalTension = 'Corruption Risk' | 'Ego Amplification' | 'System Capture' | 'Public Trust';
export type EthicalWeight = 'Low' | 'Medium' | 'High' | 'Extreme';

export interface Profession {
  id: string;
  groupId: string;
  title: string;
  brief: string;
  powerType: PowerType;
  riskLevel: RiskLevel;
  ethicalTensions: EthicalTension[];
  ethicalWeight: EthicalWeight;
  sacredThesis: string;
  ethicalFoundation: string[];
  sufiPsychology: { concept: string; manifestation: string }[];
  professionalCrisis: string[];
  operationalFramework: string[];
  accountabilityBoundaries: string[];
}

export interface ProfessionGroup {
  id: string;
  label: string;
  civilizationalDescriptor: string;
  description: string;
  color: string;
  iconName: string;
  professions: Profession[];
}

export const PROFESSION_GROUPS: ProfessionGroup[] = [
  {
    id: 'governance-law',
    label: 'Governance & Law',
    civilizationalDescriptor: 'Authority held as delegated trust',
    description: 'Power amplifies the ego faculty. Sufi ethics approaches authority as delegated trust, not personal dominion.',
    color: '#7BAFD4',
    iconName: 'Scale',
    professions: [
      {
        id: 'statesman',
        groupId: 'governance-law',
        title: 'Statesman',
        brief: 'Governance as amanah — authority held in trust, not possessed.',
        sacredThesis: 'Power is a trust held on behalf of the governed, not a reward for the powerful.',
        powerType: 'State',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'Ego Amplification', 'System Capture'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ['Justice (Adl) as foundational obligation, not procedural preference', 'Amanah: authority as a trust delegated by those governed', 'Self-restraint as the primary governance virtue', 'Accountability to principle rather than faction'],
        sufiPsychology: [
          { concept: 'Ego inflation (Kibr)', manifestation: 'Authority mistaken for personal entitlement; policy shaped by ego rather than principle' },
          { concept: 'Nafs al-Ammara', manifestation: 'The commanding self subordinating public interest to self-preservation' },
          { concept: 'Tawazun (Balance)', manifestation: 'Maintaining equilibrium between competing constituency demands without compromise of principle' },
        ],
        professionalCrisis: ['Democratic accountability replaced by populist performance', 'Institutional capture by factional interest', 'Policy optimized for re-election rather than long-term public good', 'Corruption normalized through institutional complicity'],
        operationalFramework: ['Decision audit: does this policy serve those governed or those governing?', 'Consult those most affected by decisions before finalizing them', 'Publicly articulate the ethical reasoning behind major decisions', 'Establish clear accountability mechanisms before crises occur'],
        accountabilityBoundaries: ['Authority without consent becomes coercion', 'Transparency is not optional for public trust-holders', 'Partisan loyalty cannot override constitutional obligation', 'Spiritual authority cannot substitute for institutional accountability'],
      },
      {
        id: 'judge',
        groupId: 'governance-law',
        title: 'Judge',
        brief: 'Impartiality is a sustained spiritual discipline, not a default state.',
        sacredThesis: 'Judicial authority is the most concentrated form of delegated justice.',
        powerType: 'State',
        riskLevel: 'High Authority',
        ethicalTensions: ['Ego Amplification', 'Public Trust'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ['Impartiality (Insaf) as core vocation, not procedural requirement', 'Proportionality in response — punishment fitting context, not only offence', 'Due process as ethical practice, not bureaucratic formality', "Intellectual honesty about the limits of one's own certainty"],
        sufiPsychology: [
          { concept: 'Confirmation bias (Taqlid al-Nafs)', manifestation: 'Precedent used to avoid fresh moral analysis; prior assumptions shaping interpretation of evidence' },
          { concept: 'Social pressure (Riyadha)', manifestation: 'Susceptibility to hierarchy and status in courtroom; outcomes influenced by relative power of parties' },
          { concept: 'Compassion without sentimentality (Rahma)', manifestation: 'Maintaining justice without cruelty; firmness without indifference to human suffering' },
        ],
        professionalCrisis: ['Judicial outcomes systematically correlated with race, class, and social status', 'Legal correctness mistaken for ethical correctness', 'Mandatory minimum sentencing removing proportionality from judicial practice', 'Institutional pressures to clear caseloads at the expense of due consideration'],
        operationalFramework: ['Before each significant decision, interrogate assumptions about the parties involved', 'Distinguish between what the law requires and what justice requires', 'Document reasoning transparently, including acknowledged uncertainties', 'Recuse when personal interest — however remote — is identifiable'],
        accountabilityBoundaries: ['Judicial authority cannot be insulated from public scrutiny', 'Lifetime appointments require voluntary ethical discipline proportional to unaccountability', 'The appearance of partiality damages justice as much as actual partiality'],
      },
      {
        id: 'police-officer',
        groupId: 'governance-law',
        title: 'Police Officer',
        brief: 'Force is a last resort, not a first response.',
        sacredThesis: 'The badge confers guardianship, not dominion over the community.',
        powerType: 'State',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'Ego Amplification', 'Public Trust'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Service rather than dominance as the core orientation of policing', 'Force proportionality as ethical discipline, not operational guideline', 'Community trust as the primary measure of institutional legitimacy', 'Accountability for the exercise of force — always, without exception'],
        sufiPsychology: [
          { concept: 'Authority as protection (Wilayah)', manifestation: "The officer's role is guardianship of the community, not its control" },
          { concept: 'Ego arousal under adrenaline', manifestation: 'Threat response systems that override judgment — requiring systematic training in de-escalation' },
          { concept: 'In-group loyalty vs. justice', manifestation: 'Institutional codes of silence that protect officers at the expense of accountability' },
        ],
        professionalCrisis: ['Use of force disproportionately applied across racial and socioeconomic lines', 'Accountability mechanisms systematically weakened by union structures', 'Militarization of policing changing the psychological posture of officers', 'Trauma and psychological harm in officers generating displacement behaviors'],
        operationalFramework: ['Before any use of force: ask whether it is necessary, proportionate, and accountable', 'Community relationships built before crises cannot be built during them', 'Reporting every use of force with honest written justification', 'Mandatory psychological support for officers following traumatic incidents'],
        accountabilityBoundaries: ['A badge does not confer immunity from accountability — it increases it', 'Officer welfare and community accountability are not competing values', 'The test of policing is how power is used with the powerless, not the powerful'],
      },
      {
        id: 'mediator',
        groupId: 'governance-law',
        title: 'Mediator',
        brief: 'Reconciliation as a sacred act — transforming conflict into covenant.',
        sacredThesis: 'The mediator holds space for truth to emerge between opposing parties.',
        powerType: 'Cultural',
        riskLevel: 'Moderate Authority',
        ethicalTensions: ['Ego Amplification', 'Public Trust'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Islah (reconciliation) as a sacred obligation in Islamic ethics', 'Neutrality as a disciplined practice, not a passive state', 'Confidentiality as fiduciary obligation to both parties', 'Justice orientation: the mediator serves the agreement, not the parties who pay'],
        sufiPsychology: [
          { concept: 'Nafs control under tension', manifestation: 'The mediator absorbs the emotional weight of conflict without being destabilized or taking sides unconsciously' },
          { concept: 'Sulh (peaceful settlement)', manifestation: 'The classical Sufi concept of peaceful settlement as spiritually superior to litigation — transformation over victory' },
        ],
        professionalCrisis: ['Mediation used by the powerful to avoid accountability', 'Neutrality claims concealing structural bias toward established parties', 'Confidentiality weaponized to suppress evidence of wrongdoing', 'Settlement pressure producing unjust outcomes for weaker parties'],
        operationalFramework: ['Power imbalance assessment before any mediation process begins', 'Distinguish between settlement and just settlement', 'Informed consent to mediation process and its limitations', 'Refer when power differential makes fair process impossible'],
        accountabilityBoundaries: ['Mediator neutrality cannot extend to complicity in unjust outcomes', 'Confidentiality does not protect evidence of crimes', 'Settlement is not resolution — process quality matters as much as outcome'],
      },
    ],
  },
  {
    id: 'economy-systems',
    label: 'Economy & Systems',
    civilizationalDescriptor: 'Wealth as stewardship, not extraction',
    description: 'Wealth amplifies the attachment faculty. Economic power demands proportional ethical constraint.',
    color: '#C8A75E',
    iconName: 'Briefcase',
    professions: [
      {
        id: 'businessman',
        groupId: 'economy-systems',
        title: 'Businessman',
        brief: 'Commerce as service — profit as value delivered, not extracted.',
        sacredThesis: 'Every commercial enterprise is a social institution with obligations proportional to its power.',
        powerType: 'Economic',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'System Capture'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Muamalat: business transactions governed by principles of fairness, not merely contract', 'Wealth as Amanah — stewardship obligation to those affected by commercial activity', 'Prohibition of Gharar (excessive speculation) and Riba (exploitative interest) as systemic safeguards', 'Worker dignity as foundational, not CSR afterthought'],
        sufiPsychology: [
          { concept: 'Greed (Hirs)', manifestation: 'Profit maximization displacing all other values; treating workers and communities as cost centers' },
          { concept: 'Attachment (Tama)', manifestation: 'Inability to operate at reduced margin when doing so would serve a broader good' },
          { concept: 'Gratitude (Shukr)', manifestation: 'Recognizing that commercial success is built on community infrastructure, labor, and institutions — not individual genius alone' },
        ],
        professionalCrisis: ['Shareholder primacy as ethical evasion — responsibility transferred to an abstraction', 'Supply chain ethics systematically externalized', 'Regulatory capture enabling exploitation at scale', 'Wealth inequality acceleration through compound return mechanisms'],
        operationalFramework: ['Audit: who bears the costs of this business model that are not captured in its prices?', 'Worker compensation: is it proportionate to wealth generated?', 'Environmental and community impact assessed as cost, not externality', 'Long-term viability over short-term optimization'],
        accountabilityBoundaries: ['Legal compliance is the floor, not the ceiling of ethical obligation', 'Market efficiency cannot substitute for moral judgment', 'Wealth concentration without proportional public contribution is a failure of stewardship'],
      },
      {
        id: 'economist',
        groupId: 'economy-systems',
        title: 'Economist',
        brief: 'Economic models are moral frameworks in technical disguise.',
        sacredThesis: 'Every economic model encodes values. The economist is responsible for the values they encode.',
        powerType: 'Technical',
        riskLevel: 'Distributed Influence',
        ethicalTensions: ['Ego Amplification', 'System Capture', 'Public Trust'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Epistemological humility about model limitations and distributional effects', 'Distributional justice as an integral part of economic analysis, not external political constraint', 'Transparency about whose interests are served by each analytical framework', 'Long-term systemic sustainability over short-term optimization metrics'],
        sufiPsychology: [
          { concept: 'Intellectual pride (Ujb)', manifestation: 'Mathematical formalization creating false certainty; model complexity substituting for moral responsibility' },
          { concept: 'Abstraction as evasion', manifestation: 'GDP growth metrics obscuring real distributional outcomes for identifiable populations' },
        ],
        professionalCrisis: ['Policy advice that systematically benefits capital over labor without acknowledgment', 'Austerity prescriptions that externalize suffering onto the politically marginal', 'Development economics that serves extraction over human flourishing', 'Forecasting used to normalize outcomes rather than reveal alternatives'],
        operationalFramework: ['Every policy recommendation: map who gains and who bears costs', 'Model limitations acknowledged explicitly in public-facing analysis', 'Historical track record of similar prescriptions presented with recommendations', 'Community consultation as component of economic impact assessment'],
        accountabilityBoundaries: ['Technical expertise does not exempt economists from accountability for the human consequences of their recommendations', 'Neutrality claims must be scrutinized for whose interests they naturalize'],
      },
      {
        id: 'banker',
        groupId: 'economy-systems',
        title: 'Banker',
        brief: 'Financial stewardship of others\' trust — never speculation with what belongs to the depositor.',
        sacredThesis: 'Banking is the stewardship of deferred gratification on behalf of those who trust.',
        powerType: 'Economic',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'System Capture'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ['The depositor\'s trust as primary fiduciary obligation', 'Riba prohibition as a systemic constraint against exploitative interest', 'Risk disclosure as ethical obligation, not regulatory compliance', 'Credit allocation as a social decision with distributional consequences'],
        sufiPsychology: [
          { concept: 'Wara (scrupulousness)', manifestation: 'The Sufi virtue of scrupulousness in financial dealings — refusing to benefit even from technically permissible but ethically questionable transactions' },
          { concept: 'Zuhd (detachment)', manifestation: 'Operating within financial systems without becoming captured by their logic of infinite accumulation' },
        ],
        professionalCrisis: ['Financial innovation creating risk opacity that allows privatization of gain and socialization of loss', '2008 crisis as paradigm: systemic risk manufactured and transferred to the public', 'Credit systems that amplify inequality rather than enabling productive activity', 'Regulatory capture of banking oversight by the institutions being regulated'],
        operationalFramework: ['Risk transparency: can the depositor or borrower genuinely understand what they are agreeing to?', 'Credit allocation audit: does the portfolio serve productive activity or speculation?', 'Stress testing for ethical as well as financial resilience', 'Compensation structures that align with long-term institutional health'],
        accountabilityBoundaries: ['The bank holds a social license. Its withdrawal is warranted when it violates its social function', 'Financial complexity that prevents accountability is unethical, not merely impractical', 'The depositor\'s trust cannot be subordinated to the institution\'s growth ambitions'],
      },
    ],
  },
  {
    id: 'technology-science',
    label: 'Technology & Science',
    civilizationalDescriptor: 'Mastery in service of the human, not its replacement',
    description: 'Technical mastery amplifies the control faculty. Competence demands proportional ethical responsibility.',
    color: '#8BB89A',
    iconName: 'BrainCircuit',
    professions: [
      {
        id: 'scientist',
        groupId: 'technology-science',
        title: 'Scientist',
        brief: 'Science is a trust relationship with truth.',
        sacredThesis: 'The scientist is a custodian of truth, not its owner or promoter.',
        powerType: 'Technical',
        riskLevel: 'Distributed Influence',
        ethicalTensions: ['Ego Amplification', 'Public Trust'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Intellectual honesty as the foundational scientific virtue — before peer review, before publication', 'Dual-use responsibility: the scientist is accountable for foreseeable applications of their work', 'Research integrity as a public trust, not a professional convention', 'Transparency about funding, methods, and limitations'],
        sufiPsychology: [
          { concept: 'Pride in discovery (Kibr al-Ilm)', manifestation: 'Attachment to hypothesis generating selective evidence interpretation; resistance to falsification' },
          { concept: 'Ilm (knowledge as responsibility)', manifestation: 'Knowledge in Islamic ethics is not neutral — possessing knowledge creates obligation to use it correctly' },
        ],
        professionalCrisis: ['Reproducibility crisis in multiple scientific fields driven by publication incentive structures', 'Corporate funding systematically skewing research agendas and outcomes', 'Dual-use research governance inadequate for modern biotechnology and AI capabilities', 'Scientific consensus weaponized for political purposes, eroding epistemic authority'],
        operationalFramework: ['Pre-register studies to prevent post-hoc hypothesis construction', 'Disclose all funding sources and their influence on research design', 'Actively engage with strongest counterarguments to own findings', 'Participate in public science communication as a professional obligation'],
        accountabilityBoundaries: ['Scientific authority does not extend to policy prescription — it informs it', 'The scientist bears responsibility for how their work is framed publicly', 'Conflicts of interest must be disclosed regardless of perceived impact on credibility'],
      },
      {
        id: 'ai-researcher',
        groupId: 'technology-science',
        title: 'AI Researcher',
        brief: 'Building systems affecting millions demands accountability for every design decision.',
        sacredThesis: 'AI systems have no Niyyah. Human accountability cannot be delegated to them.',
        powerType: 'Technical',
        riskLevel: 'High Authority',
        ethicalTensions: ['Ego Amplification', 'System Capture', 'Public Trust'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ['Alignment as the primary technical obligation — capability without alignment is hazard', 'Distributional impact analysis as routine component of model development', 'Transparency about capability, limitation, and intended use', 'Precautionary principle for systems whose failure modes are not fully understood'],
        sufiPsychology: [
          { concept: 'Mastery illusion (Istidraj)', manifestation: 'Technical capability generating confidence beyond domain boundaries; believing the system is aligned because it performs well on benchmarks' },
          { concept: 'Niyyah (Intent in design)', manifestation: 'Design choices encode values — the intent behind every architectural decision carries ethical weight' },
          { concept: 'Accountability without Niyyah', manifestation: 'AI systems act without intent. Human accountability cannot be delegated to them.' },
        ],
        professionalCrisis: ['Capability race dynamics preventing adequate safety evaluation before deployment', 'Workforce AI systems deployed without adequate impact assessment on affected workers', 'Bias in training data producing discriminatory outcomes at scale', 'Opacity of large model decision-making preventing meaningful accountability'],
        operationalFramework: ['Impact assessment before deployment, not after incident', 'Red-teaming as standard practice, not pre-launch formality', 'Affected community consultation as component of deployment ethics', 'Clear ownership of accountability for systems after deployment'],
        accountabilityBoundaries: ['Move fast and break things is an ethics abdication, not a methodology', "A model's performance on benchmarks does not establish its safety in deployment", 'The researcher bears moral responsibility for the systems they build regardless of organizational context'],
      },
      {
        id: 'engineer',
        groupId: 'technology-science',
        title: 'Engineer',
        brief: 'Every structure holds within it the values of those who designed it.',
        sacredThesis: 'Engineering is applied ethics — structures embody moral choices made at design time.',
        powerType: 'Technical',
        riskLevel: 'Moderate Authority',
        ethicalTensions: ['Public Trust', 'Ego Amplification'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Public safety as the primary engineering obligation — above employer interest', 'Honesty about structural limits and failure modes', 'Environmental impact as integral design constraint, not afterthought', 'Whistleblowing obligation when safety standards are compromised'],
        sufiPsychology: [
          { concept: 'Itqan (excellence in craft)', manifestation: 'The Hadith obligation to do any work with utmost excellence applies to engineering: mediocre work that endangers others is an ethical failure' },
          { concept: 'Hubris in mastery', manifestation: 'Overconfidence in calculation leading to underestimation of failure modes — the Challenger syndrome' },
        ],
        professionalCrisis: ['Cost optimization overriding safety margin standards', 'Engineers pressured to certify designs they have reservations about', 'Infrastructure inequality: superior engineering reserved for wealthy communities', 'Climate costs of construction systematically externalized'],
        operationalFramework: ['Safety margin design: what is the worst case, not the expected case?', 'Refuse to certify what you would not certify if your family used it', 'Document all safety concerns in writing regardless of employer response', 'Engage with end users — not only clients — in design review'],
        accountabilityBoundaries: ['Professional license is a public trust. It cannot be surrendered to employer direction on safety matters', 'An engineer who certifies a design they know is unsafe bears personal liability — not just organizational'],
      },
    ],
  },
  {
    id: 'knowledge-transmission',
    label: 'Knowledge & Transmission',
    civilizationalDescriptor: 'Truth as obligation, not commodity',
    description: 'Knowledge amplifies the pride faculty. The transmission of knowledge demands epistemic humility.',
    color: '#D4A07B',
    iconName: 'BookOpen',
    professions: [
      {
        id: 'teacher',
        groupId: 'knowledge-transmission',
        title: 'Teacher',
        brief: 'Teaching is the formation of human beings, not the transfer of information.',
        sacredThesis: 'The highest purpose of teaching is to make itself unnecessary.',
        powerType: 'Cultural',
        riskLevel: 'Moderate Authority',
        ethicalTensions: ['Ego Amplification', 'Public Trust'],
        ethicalWeight: 'High',
        ethicalFoundation: ['The teacher-student relationship as a sacred trust (Amanah)', 'Student intellectual autonomy as the goal — not dependence on the teacher', 'Epistemic humility: the teacher models the limits of knowledge as much as its content', 'Power differential acknowledged and governed — never exploited'],
        sufiPsychology: [
          { concept: 'Ego in authority (Kibr al-Ilm)', manifestation: 'Using the classroom as a platform for self-aggrandizement; cultivating student admiration rather than student capacity' },
          { concept: 'Tarbiyah (formation)', manifestation: 'Teaching is formation of character and capacity, not information delivery. The whole person is the subject.' },
        ],
        professionalCrisis: ['Curriculum optimized for standardized testing rather than understanding', 'Teacher authority used to suppress intellectual challenge rather than develop it', 'Emotional dependency cultivated in spiritual or academic contexts', 'Student welfare subordinated to institutional reputation'],
        operationalFramework: ["The test of good teaching is the student's capacity to challenge the teacher", 'Differentiate between the authority of knowledge and the authority of the person', 'Create conditions for student voice before expecting student engagement', 'Mentor relationships require clear boundaries — always'],
        accountabilityBoundaries: ['Spiritual or intellectual authority over students creates special vulnerability to exploitation', 'The teacher has power; the student must never be made to doubt the right to question', 'Closed systems of knowledge transmission without external scrutiny create cult dynamics'],
      },
      {
        id: 'journalist',
        groupId: 'knowledge-transmission',
        title: 'Journalist',
        brief: "The journalist's obligation is to the public record, not to any party that uses it.",
        sacredThesis: 'Journalism is a fiduciary obligation to the public truth, not a service to power.',
        powerType: 'Cultural',
        riskLevel: 'Distributed Influence',
        ethicalTensions: ['Ego Amplification', 'System Capture', 'Public Trust'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Truth as primary obligation — accuracy before speed, completeness before audience', 'Source protection as a fiduciary obligation', 'Editorial independence from institutional and commercial pressure', 'Harm minimization without censorship'],
        sufiPsychology: [
          { concept: 'Narrative ego (Hawa)', manifestation: 'The desire for a story to be true overriding the discipline to verify it' },
          { concept: 'Amr bil-Maruf (commanding the good)', manifestation: 'Journalism as a public service function — not entertainment, not advocacy, but accountability' },
        ],
        professionalCrisis: ['Revenue model collapse creating financial pressure to prioritize engagement over accuracy', 'Partisan media ecosystems where institutional identity determines coverage', 'Access journalism creating complicity with the powerful', 'Algorithmic distribution amplifying outrage over nuance'],
        operationalFramework: ['Verification before publication — always, regardless of competitive pressure', 'Source diversity: does this story reflect only one social or institutional vantage point?', 'Distinguish between what you know, what you believe, and what your source claims', 'Correction culture: errors acknowledged promptly and prominently'],
        accountabilityBoundaries: ['Audience approval cannot determine what is publishable', 'Journalistic independence requires institutional support — it cannot be maintained individually under financial pressure', 'The duty to the public record supersedes the duty to any source'],
      },
      {
        id: 'artist',
        groupId: 'knowledge-transmission',
        title: 'Artist',
        brief: 'Art is not self-expression — it is the transformation of experience into shared meaning.',
        sacredThesis: 'Beauty is a form of truth. The artist is its imperfect but necessary mediator.',
        powerType: 'Cultural',
        riskLevel: 'Distributed Influence',
        ethicalTensions: ['Ego Amplification'],
        ethicalWeight: 'Medium',
        ethicalFoundation: ['Ihsan (beauty through excellence) as a spiritual obligation in Islamic aesthetics', 'Art as service to meaning, not monument to self', 'Representation carries ethical weight — who is visible and how', 'The difference between provocation that opens understanding and provocation that exploits'],
        sufiPsychology: [
          { concept: 'Fana (self-annihilation in the work)', manifestation: 'The Sufi artistic ideal: the self disappears into the work; ego disappears into expression; the artist becomes transparent to the truth they transmit' },
          { concept: 'Jamal (divine beauty)', manifestation: 'Art that participates in Jamal illuminates the human; art that serves ego contracts it' },
        ],
        professionalCrisis: ['Art market economics reducing cultural production to financial speculation', 'Platform economics rewarding provocation over depth', 'Cultural commodification producing authenticity performance', 'AI-generated art challenging questions of attribution, labor, and meaning'],
        operationalFramework: ['Ask: does this work serve meaning or self-promotion?', 'Representation choices: who benefits and who is harmed by how this subject is depicted?', 'Attribution and credit as ethical obligations to collaborators and sources', 'Platform selection: does this channel serve the work or exploit it?'],
        accountabilityBoundaries: ['Artistic freedom does not exempt artists from responsibility for the impact of their work', 'Exploitation of vulnerable subjects for artistic purposes requires proportionally serious justification', 'Fame and market success are not validation of ethical practice'],
      },
    ],
  },
  {
    id: 'health-care',
    label: 'Health & Human Care',
    civilizationalDescriptor: 'Healing as facilitation, not control',
    description: 'Healing amplifies the messianic faculty. Clinical authority demands disciplined compassion.',
    color: '#C97B84',
    iconName: 'HeartPulse',
    professions: [
      {
        id: 'physician',
        groupId: 'health-care',
        title: 'Physician',
        brief: "Medical authority is a trust held on behalf of the patient's vulnerability.",
        sacredThesis: 'The physician facilitates healing — they do not control it. This theological frame disciplines clinical ego.',
        powerType: 'Spiritual',
        riskLevel: 'High Authority',
        ethicalTensions: ['Ego Amplification', 'System Capture', 'Public Trust'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ['Patient autonomy as the primary ethical principle — informed consent as a genuine process', 'Non-maleficence and beneficence in clinical tension — both must be held simultaneously', 'Justice in healthcare access: the physician operates within a system whose injustices they must not perpetuate', 'Epistemic humility about diagnostic certainty'],
        sufiPsychology: [
          { concept: 'Messianic ego (Kibr al-Shifa)', manifestation: "The physician's authority expanding beyond clinical role; patient as passive recipient rather than agent of own healing" },
          { concept: 'Shifa (healing) as divine attribution', manifestation: "The physician facilitates conditions for healing — they do not control it. This theological frame disciplines ego inflation." },
          { concept: 'Ihsan (excellence in attention)', manifestation: 'Every patient encounter demands full presence. Compassion fatigue is a systemic failure, not a personal one.' },
        ],
        professionalCrisis: ['Pharmaceutical industry influence on prescribing patterns and clinical guidance', 'Compassion fatigue normalized in healthcare systems with inadequate structural support', 'Diagnostic uncertainty communicated as certainty to manage patient anxiety — at the cost of informed consent', 'Racial and gender bias in pain recognition and treatment'],
        operationalFramework: ['Informed consent as genuine dialogue, not documentation', 'Acknowledge diagnostic uncertainty rather than project false confidence', 'Separate clinical judgment from commercial influence — actively', "Treat the patient's experience of illness as valid clinical data"],
        accountabilityBoundaries: ["Clinical authority ends at the patient's autonomous choice — including choices the physician would not make", 'The power differential between physician and patient demands active protection of patient agency', 'Medical error must be disclosed regardless of liability exposure'],
      },
      {
        id: 'social-worker',
        groupId: 'health-care',
        title: 'Social Worker',
        brief: 'Advocacy for the most vulnerable — against systems that produce vulnerability.',
        sacredThesis: 'The social worker stands between the vulnerable individual and systemic indifference.',
        powerType: 'State',
        riskLevel: 'Moderate Authority',
        ethicalTensions: ['System Capture', 'Public Trust'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Client self-determination as primary ethical principle', 'Structural analysis: individual problems as symptoms of systemic failures', 'Mandatory reporting as ethical tension — between client trust and child protection', 'Advocacy beyond casework: addressing the conditions that produce cases'],
        sufiPsychology: [
          { concept: 'Rahmah (compassion) without burnout', manifestation: 'Sustaining genuine compassion across caseloads that would produce numbness requires disciplined inner practice' },
          { concept: 'Structural vs individual Nafs', manifestation: 'Systems have their own Nafs — patterns of self-preservation that harm the vulnerable. The social worker must see both the individual and the system' },
        ],
        professionalCrisis: ['Caseload volumes preventing adequate service to any client', 'Child protection systems that produce secondary trauma in children they are designed to protect', 'Surveillance function conflicting with therapeutic function in same role', 'Chronic underfunding creating structural complicity with the suffering it claims to address'],
        operationalFramework: ['Client self-determination: is this intervention what the client wants, or what the system requires?', 'Document systemic failures — not only client failures', 'Set and maintain professional boundaries that preserve capacity for genuine service', 'Advocate within and beyond the organization for structural change'],
        accountabilityBoundaries: ['Professional boundaries are not self-protection — they are conditions for sustainable service', 'The duty to report cannot be used to justify surveillance that damages therapeutic relationships', 'Institutional loyalty cannot override the obligation to the client'],
      },
    ],
  },
  {
    id: 'ecology-stewardship',
    label: 'Ecology & Stewardship',
    civilizationalDescriptor: 'Khalifa — stewardship over creation',
    description: 'Stewardship of living systems demands accountability to generations not present in the decision.',
    color: '#A8C5A0',
    iconName: 'Leaf',
    professions: [
      {
        id: 'ecologist',
        groupId: 'ecology-stewardship',
        title: 'Ecologist',
        brief: 'To study living systems is to become responsible for their advocacy.',
        sacredThesis: 'The ecologist is the measurer of Mizan\'s violation — and must speak plainly about what they measure.',
        powerType: 'Technical',
        riskLevel: 'Distributed Influence',
        ethicalTensions: ['System Capture', 'Public Trust'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ["Khalifa: the ecologist bears witness to humanity's trusteeship failure and must speak plainly about it", 'Intergenerational accountability — scientific findings carry obligations beyond the researcher\'s career', 'Non-human moral consideration as a professional commitment, not personal preference', 'Policy translation responsibility: ecological science without advocacy is incomplete'],
        sufiPsychology: [
          { concept: 'Mizan (balance)', manifestation: "Ecological science documents the disruption of natural balance — the ecologist is the measurer of Mizan's violation" },
          { concept: 'Tawadu (humility)', manifestation: 'The complexity of living systems exceeds our models. Humility about uncertainty is not weakness — it is precision.' },
        ],
        professionalCrisis: ['Scientific communication constrained by funding bodies with extractive interests', 'Policy influence blocked by political systems that treat ecology as economic constraint', 'Researcher burnout from witnessing accelerating ecosystem loss without systemic response', 'Career incentives that reward narrow publication over systemic advocacy'],
        operationalFramework: ['Translate findings into policy-accessible language as part of research responsibility', 'Maintain connections with affected communities, not only peer networks', 'Disclose funding sources and their potential influence on research framing', "Engage publicly with findings — the public's right to know is part of the ecologist's obligation"],
        accountabilityBoundaries: ['Scientific objectivity cannot become moral passivity in the face of ecological collapse', "The ecologist's accountability extends to future generations who cannot advocate for themselves"],
      },
      {
        id: 'architect',
        groupId: 'ecology-stewardship',
        title: 'Architect',
        brief: 'Built environments shape the inner lives of those who inhabit them.',
        sacredThesis: 'Every building is a moral statement about who matters and how they should live.',
        powerType: 'Cultural',
        riskLevel: 'Moderate Authority',
        ethicalTensions: ['Public Trust', 'Ego Amplification'],
        ethicalWeight: 'Medium',
        ethicalFoundation: ['Sacredness of space: Islamic architecture as the integration of function and transcendence', 'Inhabitant welfare as primary design criterion over client aesthetic preference', 'Environmental obligation: buildings as nodes in ecological systems', 'Equity in design: refusing to design spaces that exclude or diminish'],
        sufiPsychology: [
          { concept: 'Sacred geometry as ethics', manifestation: 'The Islamic architectural tradition encodes cosmological principles in built form — proportion, orientation, light, and space as expressions of divine order, not mere aesthetics' },
          { concept: 'Architect ego in starchitecture', manifestation: 'Buildings as monuments to the designer rather than gifts to the inhabitants — the inversion of the service orientation' },
        ],
        professionalCrisis: ['Developer-driven design systematically prioritizing density and profit over habitability', 'Luxury development in cities displacing existing communities', 'Climate costs of construction materials and building operation not integrated into design ethics', 'Accessibility treated as regulatory compliance rather than design priority'],
        operationalFramework: ['Who will live in this building and how? Design for the inhabitant, not the rendering', 'Environmental impact assessment as design input, not post-design compliance', 'Engage future inhabitants in design process — not only commissioning clients', 'Accessibility and dignity of access as design requirements from the beginning'],
        accountabilityBoundaries: ["The architect's license is a public trust for the built environment, not merely a client-service credential", 'Design that harms inhabitable environments or communities cannot be justified by client instruction'],
      },
    ],
  },
  {
    id: 'security-defense',
    label: 'Security & Defense',
    civilizationalDescriptor: 'Lethal authority held under moral law',
    description: 'Lethal authority is the most concentrated form of institutional power. Its ethical constraints are proportionally demanding.',
    color: '#9B9B9B',
    iconName: 'Shield',
    professions: [
      {
        id: 'soldier',
        groupId: 'security-defense',
        title: 'Soldier',
        brief: 'Military service is a moral act, not merely an institutional function.',
        sacredThesis: 'The obligation to refuse unlawful orders is not insubordination — it is moral law.',
        powerType: 'State',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'Ego Amplification'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ['Just war doctrine: the legitimacy of military action depends on its justification, conduct, and proportion', 'International humanitarian law as the minimum ethical floor — not the ceiling', 'Obligation to refuse unlawful orders — this is not insubordination, it is moral law', 'Non-combatant protection as an absolute constraint, not a tactical consideration'],
        sufiPsychology: [
          { concept: 'Nafs al-Ammara under threat', manifestation: 'Combat stress activating the commanding ego — revenge, dehumanization of the enemy, moral injury accumulation' },
          { concept: 'Jihad as inner discipline', manifestation: 'Classical Islamic military ethics: the greater Jihad is self-mastery. External conflict is secondary to internal discipline.' },
        ],
        professionalCrisis: ['Moral injury from participation in conflicts whose justification is contested', 'Drone warfare and remote lethal action detaching operators from the moral weight of killing', 'Veteran reintegration failures when moral injury is untreated', 'Contractor ecosystems that remove accountability from military operations'],
        operationalFramework: ['Know the legal and ethical basis for every operation before executing it', 'Report crimes of war — this is not optional for military personnel', 'Seek psychological support for moral injury — this is a professional obligation', 'Chain of accountability must be traceable to identifiable human decision-makers'],
        accountabilityBoundaries: ['Following orders is not a defense for participation in crimes against civilians', 'The weight of lethal authority demands proportional ethical preparation — not just operational training', 'Honor requires acknowledgment of wrongdoing, not its concealment'],
      },
      {
        id: 'cyber-guardian',
        groupId: 'security-defense',
        title: 'Cyber Guardian',
        brief: 'Defending digital infrastructure is defending the foundations of modern civil life.',
        sacredThesis: 'Cyber security is guardianship of the digital commons on which civilization now depends.',
        powerType: 'Technical',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'System Capture'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Privacy as a foundational right — security cannot justify mass surveillance', 'Proportionality: defensive necessity determines offensive tool deployment', 'Dual-use code ethics: exploit development creates weapons of dual application', 'Transparency to those whose systems are defended'],
        sufiPsychology: [
          { concept: 'Hidden power and accountability', manifestation: 'Cyber capabilities operate invisibly — this opacity creates conditions for unaccountable exercise of power that requires proportionally greater internal discipline' },
          { concept: 'Amana of access', manifestation: 'System access is a trust. The guardian who has access to all has a proportionally greater obligation than one who has access to little' },
        ],
        professionalCrisis: ['Surveillance capitalism creating infrastructure for authoritarian repression', 'Offensive capability development outpacing defensive standards and governance', 'Private cyber contractors selling capabilities to the highest bidder regardless of purpose', 'Zero-day market incentivizing vulnerability hoarding over systemic security improvement'],
        operationalFramework: ['Offensive tool development: map every plausible misuse scenario before deployment', 'Privacy impact assessment as standard component of security architecture', 'Responsible disclosure: vulnerabilities reported to vendors before public or offensive use', 'Audit trail for all defensive access to others\' systems'],
        accountabilityBoundaries: ['Security authority cannot justify privacy violation at scale', 'Capabilities developed for defense cannot be sold without regard for their application', 'The cyber guardian\'s accountability extends to what their tools enable, not merely what they personally do'],
      },
    ],
  },
  {
    id: 'institutional-leadership',
    label: 'Institutional Leadership',
    civilizationalDescriptor: 'Institutions as vehicles for principled purpose',
    description: 'Institutional authority creates systemic influence. Its responsibilities are proportionally systemic.',
    color: '#B8A97A',
    iconName: 'Building2',
    professions: [
      {
        id: 'chancellor',
        groupId: 'institutional-leadership',
        title: 'Chancellor',
        brief: 'Leading an institution of knowledge is a trust held on behalf of truth.',
        sacredThesis: 'The university holds a trust on behalf of knowledge itself — not merely its students, funders, or reputation.',
        powerType: 'Institutional',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'Ego Amplification', 'System Capture'],
        ethicalWeight: 'Extreme',
        ethicalFoundation: ['Academic freedom as an institutional obligation — not merely a professor\'s right', 'Institutional integrity over institutional reputation — they are not the same', 'Transparency about financial arrangements that create conflicts of interest', 'Student welfare as the primary institutional obligation, not endowment growth'],
        sufiPsychology: [
          { concept: 'Institutional ego', manifestation: 'Prestige optimization displacing mission; rankings above genuine educational quality' },
          { concept: 'Amanah of scholarship', manifestation: "The university holds a trust on behalf of knowledge itself — not merely its students, funders, or reputation" },
        ],
        professionalCrisis: ['Corporatization of university governance reducing faculty shared governance', 'Institutional prestige protecting powerful faculty accused of misconduct', 'International funding relationships creating political constraint on academic expression', 'Student mental health crisis ignored in favor of admissions marketing'],
        operationalFramework: ['Governance structures that genuinely distribute power — not performative faculty consultation', 'Transparent reporting of donor conditions and their potential influence on institutional decisions', 'Student and faculty welfare metrics weighted alongside financial metrics in leadership evaluation', 'Succession planning that institutionalizes values, not just administrative procedures'],
        accountabilityBoundaries: ["The chancellor's primary accountability is to the institution's mission, not its donors", 'Institutional reputation management cannot override individual accountability for misconduct', 'The test of institutional integrity is how it behaves when accountability is costly'],
      },
      {
        id: 'trustee',
        groupId: 'institutional-leadership',
        title: 'Trustee',
        brief: 'Fiduciary duty is a spiritual obligation, not merely a legal one.',
        sacredThesis: 'The trustee holds the institution\'s future on behalf of those who cannot yet speak for it.',
        powerType: 'Institutional',
        riskLevel: 'High Authority',
        ethicalTensions: ['Corruption Risk', 'System Capture'],
        ethicalWeight: 'High',
        ethicalFoundation: ['Fiduciary duty as a sacred trust — the trustee acts for the beneficiary, not for themselves', 'Long-term institutional health over short-term financial optimization', 'Governance independence: the trustee\'s first loyalty is to the institution\'s mission', 'Conflict of interest identification and recusal as routine obligations'],
        sufiPsychology: [
          { concept: 'Waqf ethics', manifestation: 'The classical Islamic endowment institution — Waqf — models the trustee obligation: assets held permanently for stated purpose, resistant to private capture' },
          { concept: 'Istikhlaf (delegated stewardship)', manifestation: 'The trustee is not the owner — they are a temporary steward of something that belongs to a larger purpose' },
        ],
        professionalCrisis: ['Trustees selected for wealth rather than governance capability or ethical judgment', 'Donor-trustee relationships creating captured governance', 'Boards rubber-stamping executive decisions rather than providing genuine oversight', 'Trustee conflicts of interest inadequately disclosed or managed'],
        operationalFramework: ['Governance independence test: would you vote the same way if your financial relationship with the institution were severed?', 'Long-term mission alignment audit: do current activities reflect the institution\'s foundational purpose?', 'Succession planning that preserves governance independence', 'External governance review as routine practice'],
        accountabilityBoundaries: ['Trustee authority exists to protect the institution\'s mission — not to serve trustee interests', 'Board loyalty to the CEO is a governance failure when it substitutes for loyalty to the mission', 'The fiduciary obligation extends to those who depend on the institution, not only to those who govern it'],
      },
    ],
  },
];

export function getAllProfessions(): Profession[] {
  return PROFESSION_GROUPS.flatMap(g => g.professions);
}

export const ETHICAL_WEIGHT_ORDER: EthicalWeight[] = ['Low', 'Medium', 'High', 'Extreme'];
export const POWER_TYPES: PowerType[] = ['State', 'Economic', 'Cultural', 'Spiritual', 'Technical', 'Institutional'];
export const RISK_LEVELS: RiskLevel[] = ['High Authority', 'Moderate Authority', 'Distributed Influence'];
export const ETHICAL_TENSIONS: EthicalTension[] = ['Corruption Risk', 'Ego Amplification', 'System Capture', 'Public Trust'];
